apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-23T08:41:28Z"
  generateName: controller-agent-upgrade-
  labels:
    controller-revision-hash: 77f94b8994
    operator.kubeadm.x-k8s.io/operation: upgrade
    operator.kubeadm.x-k8s.io/uid: 07f901b5-aa85-11ec-bff8-aa1770338b9c
    pod-template-generation: "1"
  name: controller-agent-upgrade-p2dn7
  namespace: operator-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: controller-agent-upgrade
    uid: d1dd1eb5-e7b2-49a1-9904-8a6c05eca94d
  resourceVersion: "3818302"
  uid: d12c8c88-ae5a-4be2-b1dc-bfb110cfd56f
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - a010735
  containers:
  - args:
    - --mode=agent
    - --agent-node-name=$(MY_NODE_NAME)
    - --agent-operation=upgrade
    - --metrics-addr=127.0.0.1:8080
    command:
    - /manager
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: jungler/controller:latest
    imagePullPolicy: Always
    name: agent
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /usr/bin/kubeadm
      name: kubeadm-binary
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-87hzq
      readOnly: true
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=10
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      hostPort: 8443
      name: https
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-87hzq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: a010735
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /usr/bin/kubeadm
      type: File
    name: kubeadm-binary
  - hostPath:
      path: /etc/kubernetes
      type: Directory
    name: etc-kubernetes
  - name: kube-api-access-87hzq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T08:41:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T08:41:34Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T08:41:34Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T08:41:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5c2eff38ce7a9ed84e142d563871f596b2faf12ea7924fd58223fc1a3165d685
    image: jungler/controller:latest
    imageID: docker-pullable://jungler/controller@sha256:64ae84d8804ccb0a6ff723fac75551f739e5b079805d04e4aa9b34fc07e34aae
    lastState: {}
    name: agent
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-23T08:41:33Z"
  - containerID: docker://24bc965fa5ca6ccd9484daee9f5d4aac6f40354c16c1bdf59f4288198c6e2dec
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
    imageID: docker-pullable://gcr.io/kubebuilder/kube-rbac-proxy@sha256:297896d96b827bbcb1abd696da1b2d81cab88359ac34cce0e8281f266b4e08de
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-23T08:41:33Z"
  hostIP: 10.169.180.51
  phase: Running
  podIP: 10.169.180.51
  podIPs:
  - ip: 10.169.180.51
  qosClass: Burstable
  startTime: "2022-03-23T08:41:28Z"
