apiVersion: v1
items:
- apiVersion: operator.kubeadm.x-k8s.io/v1alpha1
  kind: RuntimeTaskGroup
  metadata:
    creationTimestamp: "2022-05-09T08:11:18Z"
    generation: 1
    labels:
      operator.kubeadm.x-k8s.io/operation: upgrade
      operator.kubeadm.x-k8s.io/order: "01"
      operator.kubeadm.x-k8s.io/taskgroup: upgrade-cp-1
      operator.kubeadm.x-k8s.io/uid: 9a12425f-cf6f-11ec-adbf-9a9faa93445b
    name: upgrade-01-upgrade-cp-1
    ownerReferences:
    - apiVersion: operator.kubeadm.x-k8s.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Operation
      name: upgrade
      uid: 8fa2df45-b28c-4680-9ccb-65a532ae4871
    resourceVersion: "11289647"
    uid: 8152c1cc-48d6-4c6f-a722-74604dcfaa80
  spec:
    nodeFilter: Head
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
    selector:
      matchLabels:
        operator.kubeadm.x-k8s.io/operation: upgrade
        operator.kubeadm.x-k8s.io/order: "01"
        operator.kubeadm.x-k8s.io/taskgroup: upgrade-cp-1
        operator.kubeadm.x-k8s.io/uid: 9a12425f-cf6f-11ec-adbf-9a9faa93445b
    template:
      metadata: {}
      spec:
        commands:
        - upgradeKubeadm: {}
        - kubeadmUpgradeApply: {}
        - upgradeKubeletAndKubeactl: {}
  status:
    nodes: 1
    phase: Running
    startTime: "2022-05-09T08:11:18Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
